apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-zobv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/karthik-jk-tenant/dc-metro-map-2/dc-metro-map-zobv@sha256:f8c55aa52477ec1b3cb3b806d21f875b33e3764736cf17e92e78789225cf895a
        name: container-image
        resources: {}
status: {}
