apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-zobv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-zobv
    app.kubernetes.io/part-of: dc-metro-map-2
  name: dc-metro-map-zobv1dvl
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dc-metro-map-zobv
    weight: 100
status: {}
